- policies/image/policy/optional-labels.rego
This adds a policy for optional labels `maintainer` and `summary` for HACBS-201
> Add optional label policy

- policies/clair/vulnerabilities-check.rego
Rego file consisting of vulnerabilities check:
Sample output:
`./conftest test --policy clair-vulns.rego test-index.json -o json`
```[
{
"filename": "test-index.json",
"namespace": "main",
"successes": 1,
"failures": [
{
"msg": "The packages musn't have any high vulnerabilities! Packages with high vulnerabilities: bind-libs, bind-libs-lite, bind-license, bind-utils, glib2, gnutls, nettle, openssl-libs, python3-bind, systemd, systemd-libs, systemd-pam"
},
{
"msg": "The packages musn't have any low vulnerabilities! Packages with low vulnerabilities: bash, libdb, libdb-utils, libpcap, openssl-libs, systemd, systemd-libs, systemd-pam"
},
{
"msg": "The packages musn't have any medium vulnerabilities! Packages with medium vulnerabilities: bind-libs, bind-libs-lite, bind-license, bind-utils, …
```
> [HACBS-74]-adding clair vulnerability policies

- policies/clair/vulnerabilities-check.rego
- policies/image/deprecated-labels.rego
- policies/image/optional-labels.rego
- policies/image/required-labels.rego
- policies/repository/deprecated-image.rego
- policies/rpm_manifest/unsigned-rpms.rego
* Split up the policies according to the data they test
* Set the required_checks and optional_checks packages
This is a proposal to put the policies into different directories according to the data that they are supposed to validate(`image`, `repository`, `clair`, `rpm_manifest`).
Additionally, this change proposes setting the package name for each policy to be either `required_checks` or `optional_checks` to allow differentiation when running them together from the same directory.
> Proposal: Refactor the policy structure

- .github/workflows/README.md
- .github/workflows/release.yaml
version - has to be specified while manually triggering the release workflow.
latest - points to latest image version.
sha - SHA256 digest
Signed-off-by: Sri Vignesh [sselvan@redhat.com](mailto:sselvan@redhat.com)
> Add release-workflow to hacbs-test repo

- Dockerfile
This adds prerequisites for HACBS-223 (go, gosec and git (for git cloning the source repo)).
> Add gosec to hacbs-test Docker image

- .github/workflows/clair-in-ci-db.yaml
Multiple reasons why the build image was not passing throught a workflow job:
Since the scale of build image exceeded 11GB, it was unable to finish the build process (no space left on device).
This problem persisted even though the enough space was provided. 
Removing `buildah` section helped to solve this issue together with adding some space within the github runner.
We also don't need to provide a support for multiple architectures at this time, hence the removal of qemu.
Maybe worth mentioning adding this github action https://github.com/marketplace/actions/free-disk-space-ubuntu
in near future.
> fix[HACBS-840] provide space for docker build

- test/entrypoint.sh
The latest `registry.access.redhat.com/ubi8/ubi` image is missing the required 'com.redhat.build-host' label, thus failing our integration tests.
* Use redhat-appstudio/sample-image:test-index-pass
> fix: change image used for labels in integration tests

- Dockerfile
- test/entrypoint.sh
- test/utils.sh
Add a function to parse hacbs test result to generate $HACBS_TEST_OUTPUT
and log out failed tests
> feat(HACBS-1386): a script to parse hacbs test result

- Dockerfile
DNF cache is useless in final image, by removing it we can save disk space and make image smaller.
Currently it saved about 30MB
Signed-off-by: Martin Basti <mbasti@redhat.com>
> fix(none): Remove DNF cache in container image

- test/utils.sh
- unittests_bash/test_utils.bats
At the end this function is unused, removing dead code
Signed-off-by: Martin Basti <mbasti@redhat.com>
> feat(HACBS-1598): Remove unused function `make_error_result_json`

- Dockerfile
oc.tar.gzip archive is not needed anymore after isntallation, removing it saves about 51MB of the image size
Signed-off-by: Martin Basti <mbasti@redhat.com>
> fix(Dockerfile) remove unused tar.gz archive

- .github/workflows/pr-checks.yaml
building clamav and clair image takes long time, run tests only when there were changes related to those images
Signed-off-by: Martin Basti <mbasti@redhat.com>
> fix(CI): run image builds conditionaly

- clair-in-ci/Dockerfile
Addressing https://issues.redhat.com/browse/PROJQUAY-4878 this removes the pre-compiled DB fetch and forces the container to do the DB creation. This is required as the infra for serving the pre-compiled DB is going away. Also, update the clair-action version. This will increase the time it takes to produce the image as it will be reaching out directly to Clair's sources, but given it is run daily that shouldn't be an issue. This also means that errors in the update cycle will be transparent in the Actions instead of hidden (as they are now).
Signed-off-by: crozzy <joseph.crosland@gmail.com>
> clair: Update Dockerfile to build DB

- .github/dependabot.yml
This dependabot can detect dependencies version update and create pr for them automatically, more details can be found in https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuring-dependabot-version-updates
This is the first PR to use dependabot, we just make it detect the docker image version update.
[Here](https://github.com/hongweiliu17/dependabot-test/blob/main/.github/dependabot.yml) is the merged dependatbot in my personal repo and it generates [two PRs](https://github.com/hongweiliu17/dependabot-test/pulls) to update docker image in my repo.
> feat(HACBS-1536): add dependabot to detect dependencies update

- Dockerfile
Including pinned version of OPM from verified source.
Version : v1.26.3
> fix(HACBS-1755) add pinned opm version from gh repo

- Dockerfile
Pin snyk image to prevent unvanted breaking changes. Each change must be proposed via PR and pass CI tests.
Note: digest will be updated by dependabot when new image is released
> fix(Dockerfile): pin snyk image

- clair-in-ci/Dockerfile
* Use quay.io/projectquay/clair-action:v0.0.4 version
* Set the log level to 'info' when running update
* Info logs produce ~2k lines, used for tracking sources
> feat(PROJQUAY-5085): use clair-action with lower logging

- .github/workflows/clair-in-ci-db.yaml
Currently the runner is running out of space because it is pulling down a image first and retagging it. This should delete that image after the retagging and give Clair enough space to do the update.
> clair: Free space for Clair to create DB

- policies/image/required-labels.rego
- unittests/test_images/required-labels_test.rego
Fixes [HACBS-1929](https://issues.redhat.com/browse/HACBS-1929)
Delete the policy which mandates the presence of the `com.redhat.build-host` label during the sanity-labels taskrun.
> fix(HACBS-1929): delete a label check policy

- policies/clair/vulnerabilities-check.rego
- unittests/test_clair/vulnerabilities-check_test.rego
- unittests/test_data/clair.json
example output after the change:
```
[jsztuka@fedora hacbs-test]$ conftest test --no-fail ~/Documents/playground/tkn/clair-result.json --policy policies/clair/vulnerabilities-check.rego --namespace required_checks --output=json
[
{
"filename": "/home/jsztuka/Documents/playground/tkn/clair-result.json",
"namespace": "required_checks",
"successes": 1,
"failures": [
{
"msg": "Found packages with high vulnerabilities. Consider updating to newer version of those packages, they may not longet be affected by the reported CVEs. You can check clair logs for more infromation. Packages found: expat, krb5-libs, libksba, python39, python39-libs, systemd, systemd-libs, systemd-pam, urllib3, wheel, xz-libs",
"metadata": {
"details": {
"description": "The image shouldn't contain packages that have high …
```
> fix(stoneintg-358|stonebugs-42):drop URL & report number of vulns

- test/selftest.sh
- test/utils.sh
- unittests_bash/test_utils.bats
This PR will unblock failures such:
https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/redhat-appstudio_build-service/149/pull-ci-redhat-appstudio-build-service-main-build-service-e2e/1653317992936640512
Function to parse output name will be changed in another PR since it would mean to also change build-def side at this moment and also more time to changes to take place.
> fix(utils): remove hacbs prefix from result

- .github/workflows/pr-checks.yaml
Add `pipefail` option to our shell in policy unit test step to ensure proper failure handling by GitHub Action workflow.
> fix(STONEINTG-361): policy unit tests doesn't emit failure

- policies/clair/vulnerabilities-check.rego
- unittests/test_clair/vulnerabilities-check_test.rego
- unittests/test_data/clair.json
Clair rego policy will work now with pairs RPM and their vulnerabilities on the particular severity level. Insted of counting number of affected RPMs, it will report number of vulnerabilities (i.e. more than RPMs if single RPM has more vulnerabilities).
This behavior is more aligned with quay.io reporting
Adressing issues:
* Clair provides "duplicated" CVEs when violation comes from multiple repo sources, only unique CVE is counted.
* Number of unique CVEs per RPM is counted instead of plain number of affected RPMs; aggregated as sum of all vulnerabilites per RPM on the same severity level
* Description also contains list of CVE names affecting RPM
> fix(STONEINTG-375): reporting of clair CVEs

- .github/workflows/pr-checks.yaml
We can test only pullrequests with current implementation. For push events we would need to use diffrent variables (`github.event.push.*`)
So far testing only PR is good and we don't need more complicated implementations
> chore(gitlint): test only pullrequests

- .github/workflows/pr-checks.yaml
Resolves issue of buildah breaking podman if the Containerfile has any `run` commands.
> fix(pr-checks): Build the hacbs-test image in GH actions with podman

- test/conftest.sh
STONEINTG-360 modified Clair rego policy to return warnings as opposed to violations. This caused integration tests to fail when expecting a failed status return.
> fix(test): integration test fails on false negative for clair

- Dockerfile
Cyclonedx-cli is causing failures after updating syft version and it is not up to date. Sbom-utility does the same thing, with the same commands, it is also maintained by cyclonedx, but it is more up to date and written in Go.
> chore(Dockerfile): add sbom-utility

- .github/workflows/clam-db.yaml
Instead of keeping previous version under floating tag "previous", just push image into registry using unique tag and keep it there (old images can be removed manually/automatically later).
We don't need to pull image anymore, just tag it with floating tag.
This also fixes the issue, where the backup tag haven't had all architecture, just the x86_64.
Images are also using both tags latest (for bw compatibility) and v1 for future to allow us do a breaking change and relese major version.
> fix(STONEINTG-31): clamDB image: use unique tags

- .github/workflows/pr-checks.yaml
- Dockerfile
Update the opa package and modify dockerfile to allow dependabot to monitor conftest going forward. Note, dependabot is NOT watching opa versioning.
> feat(STONEINTG-429): pin conftest image & update opa version

- Dockerfile
Remove tag to track latest version for conftest and instead pin to 0.44.1
> fix(STONEINTG-429): remove latest tag and pin confftest version

- Dockerfile
- clamav/Dockerfile
Changing base image from ubi > ubi minimal.
Old ClamavDB image: 463 MB
New ClamavDB image:  381 MB
Old habcs-test image: 749 MB
New hacbs-test image: 669 MB
Clair in action image has already ubi-minimal as a base image, so no changes are required there.
> feat(STONE-254): use ubi-minimal as base img

- test/selftest.sh
- test/utils.sh
* set euo to shell to fail on error early
* add trap to show linenumber of err
Signed-off-by: Hongwei Liu <hongliu@redhat.com>
> feat(STONEINTG-222) set euo to shell to fail on error early

- test/utils.sh
* ERR can't handle the syntax error like undefined variable in our hasbs-test image, so use EXIT. See https://stackoverflow.com/questions/58317346/err-trap-is-not-executed-when-syntax-error
Then it can be used as below to catch nonexisting file error
```
trap 'handle_error "TEST_OUTPUT"' EXIT
cat nonexisting_file
```
or undefined variable
```
trap 'handle_error "TEST_OUTPUT"' EXIT
echo $undefined_variable
```
Signed-off-by: Hongwei Liu <hongliu@redhat.com>
> fix(STONEINTG-222): fix pr 137

- policies/clair/vulnerabilities-check.rego
- unittests/test_clair/vulnerabilities-check_test.rego
* Add warn_unknown_vulnerabilities to catch vulnerabilities of Unkown severity level from the clair scan output
* Update unit tests to account for the new rule
> feat(STONEINTG-425): add unknown vulnerabilities for clair

- .github/workflows/pr-checks.yaml
* Align OPA version in pr-checks with conftest v0.45.0
* Follow-up on #136
> chore: use OPA v0.56.0

- Dockerfile
* The conftest images in dockerhub don't have a ppc64le version, causing failures when releasing the image
* This change reverts to downloading the binary from gitHub, with the comment to also update the pr-checks OPA version
> fix: revert to downloading conftest binary

- Dockerfile
* The ubi-minimal is missing the findutils package This is required for fbc check tasks
> fix(STONEINTG-254): add missing findutils

- test/utils.sh
This unintentionally enables strict mode in all tasks which aren't ready for it
> fix(STONEINTG-634): don't set -euo pipefail in shared lib

- policies/repository/deprecated-image.rego
- unittests/test_repository/deprecated-image_test.rego
* Use the Container image release categories article which holds a concise and long-lived definition for 'deprecated' as well as being publicly available
* Replace reference to COMET with Red Hat Catalog
> fix(STONEINTG-663): update URL and description for deprecated images

- .github/workflows/build_reusable.yaml
- .github/workflows/pr-checks.yaml
- .github/workflows/release.yaml
- Dockerfile
- test/selftest.sh
Make sure that both workflows are building and testing the same architectures in the same way.
Changes:
* New nested workflow has been created, to be used in both PR and
release workflows. It builds and tests hacbs-test image (push is
disabled by default)
* Builds image using buildah and emulation for all specified architectures
* Tests image using podman with emulation per each architecture
> fix(STONEINTG-624): align PR and release workflow

- Dockerfile
This binary is not used anymore by tekton tasks in build-definitions, we only kept it here for 3+ months to prevent any accidental breaking of functionality.
Time to remove it has come.
> chore(STONEINTG-673): remove cyclonedx binary

- Dockerfile
This package is not needed anymore, python code using this has been dropped from build-definitions
https://github.com/redhat-appstudio/build-definitions/pull/782
> feat(STONEINTG-755): remove python-dateutil

- .github/dependabot.yml
We don't need daily udpates, that would trigger too many updates for nothing, as we are not releasing so often.
> chore(dependabot): update images weekly

- Dockerfile
ubi8 have old glibc and doesn't work with some rhel9 tools. Updating to rhel9 to support newer glibc
> feat(STONEINTG-823): upgrade to ubi9 base image

- test/utils.sh
- unittests_bash/test_utils.bats
Refers to CVP-4050. Rename get_image_index_manifests to get_image_manifests and it should return a map of arch to digest for both image indexes and image manifests.
> feat: get_image_manifests func for image index and image manifest

- test/utils.sh
- unittests_bash/test_utils.bats
Previously, the get_image_manifests was getting the `digest` for the image manifest using `skopeo inspect --raw | jq .config.digest` . That is not the digest of the image. This commit fixes it
> fix: Get correct digest for image manifest in get_image_manifests

- .github/workflows/clam-db.yaml
- clamav/Dockerfile
- clamav/whitelist.ign2
Whitelisting `Win.Virus.Expiro-10026576-0` as this signature is making false positive alerts.
> feat(clamav): add whitelist

- .github/workflows/clam-db.yaml
Allow to run build workflow manually in case that early rebuild of image is needed.
> chore(clamDB): allow manual rebuild

- Dockerfile
- test/selftest.sh
cosing tool is needed to fetch and parse SBOM for the built image
SBOM will be used in deprecated-image-check task
> feat(STONEINTG-887): add cosign binary

- .github/workflows/release.yaml
Default github token is used for action. We need token with higher privileges and rather than modify default token, let's explicitly set token.
> fix(release): explicitly specify token

- test/utils.sh
Update make_result_json function to implement timestamp in RFC3339 date format to comply with ADR-30.
Example output of updated call to date: `2024-06-10T15:36:05+00:00`
> feat(STONEINTG-659): task TEST_OUTPUT returns RFC3339 date format

- clamav/Dockerfile
Tested via manual triggering of workflow within fork. The specific workflow can be found [here](https://github.com/konflux-ci/konflux-test/blob/main/.github/workflows/clam-db.yaml)
> feat(STONEINTG-605) updated clamav Dockerfile to ubi9

- .github/workflows/clam-ver-check.yaml
Adding daily clamav version checker that will get triggered every day in 6:00 AM.
In case it detects a newer version in rpm repo, it will run a new konflux-test image release.
> feat(STONEINTG-1031):add daly clamav version checker

- Dockerfile
csdiff and git packages are installed in order to be used by SAST tasks to parse the results and generate fingerprinting.
This will be used by future SAST tasks provided by the OpenScanHub team, for example: https://issues.redhat.com/browse/OSH-737
> feat: Added csdiff and git packages

- Dockerfile
python3-file-magic package is installed in order to be used 
by SAST tasks to run find-unicode-control tool
Signed-off-by: Chuntao Han <chhan@redhat.com>
> feat: added python3-file-magic package

- Dockerfile
csmock-plugin-shellcheck provides script to run shellcheck on a directory tree, which will be needed in the sast-shell-check task
Related jira issue: https://issues.redhat.com/browse/OSH-738
> feat(Dockerfile): add ShellCheck/csmock-plugin-shellcheck for sast scan

- Dockerfile
This changes the Dockerfile to pull the cosign container image from GHCR instead of Google Cloud. This helps the Sigstore team manage their cloud spend (as GHCR is provided for free and Google Cloud Artifact Registry is not).
Note the container hash does not change and images are posted to both locations upon cosign's release process.
> chore(Dockerfile): switch cosign registry from GCR to GHCR

- .github/workflows/clam-db.yaml
this PR is part of the effort to migrate  quay repo  to konflux-ci/clamav-db ,  on this step we add the new repo 
so the clamav-db images will be pushed for both repos, once we see it works as expected then the old one will be decoupled
[STONEINTG-947](https://issues.redhat.com/browse/STONEINTG-947)
> feat(STONEINTG-947): migrating clamav-db to konflux-ci in quay

- Dockerfile
Required for a new Konflux task:  FIPS static check
CVP-4332
> feat(CVP-4332): Install umoci to konflux-test image

- .github/workflows/clam-db.yaml
this PR is a continues work and last phase of  [STONEINTG-947](https://issues.redhat.com/browse/STONEINTG-947)
its for replacing the new repo within the workflow of Github Action pushing img of task Clamav DB
> feat(STONEINTG-947): replace the old quay repo with the new konflux-ci

- Dockerfile
- test/utils.sh
- unittests_bash/test_utils.bats
Operator tests require the functionality to extract unreleased bundle image from FBC fragments. This commit adds a function that can be reused in multiple tekton tasks
> feat(CVP-4340): add function to get unreleased bundles in utils

- test/utils.sh
- unittests_bash/test_utils.bats
for some fragments and index images, the output of opm render command contains control characters when stored in a bash variable. This commit fixes that by cleaning the output before running jq on it
> fix(CVP-4340): handle control chars in OPM output

- test/utils.sh
- unittests_bash/test_utils.bats
this commit adds two helper functions named get_image_labels and extract_related_images_from_bundle to avoid code duplicatioin in build-definitions tasks
> feat(CVP-4333): add helper functions for fips operator checks

- test/utils.sh
- unittests_bash/test_utils.bats
This commit adds two functions, first is process_image_digest_mirror_set which takes imageDigestMirrorSet as yaml and returns a map of source and mirrors. The second is replace_image_pullspec which replaces the image registry and repo with that of a mirror.
> feat(CVP-4333): add more helper functions for FIPS check

- Dockerfile
* Set cosign back to the latest released version
> fix: revert cosign to v2.4.1

- test/utils.sh
- unittests_bash/test_utils.bats
This commit adds two functions:
* **get_package_from_catalog**: Given an output of 'opm render fbcFragment' command it returns a package name.
* **get_channel_from_catalog**:  Given an output of 'opm render fbcFragment' command and a olm.package name it returns the 'defaultChannel' value specified in the olm.package entry
* **get_highest_bundle_version**:  Given an output of 'opm render fbcFragment' command, package and channel it returns the highest bundle version
All functions will be used in the task of a 'deploy-fbc' pipeline in https://github.com/konflux-ci/tekton-integration-catalog
Signed-off-by: asergienk [asergien@redhat.com](mailto:asergien@redhat.com)
> feat(CVP-4395,CVP-4396): add get package, channel and highest bundle functions in utils

- test/utils.sh
- unittests_bash/test_utils.bats
Adding more functionality to the utils scripts in order to then reduce
the amount of duplication in task scripts within build-definitions
including:
* Parsing pullspecs
* Getting pullspecs in various forms of digest and tag
* Getting the base image
* Getting a matching FBC catalog image
* Rendering a catalog and reusing the cached output
Combining logic for extracting unique differential properties between a
FBC fragment and its matching catalog image
* Extracting unique bundles from the catalog
* Extracting related images from the catalog
fixes #353
Signed-off-by: arewm <arewm@users.noreply.github.com>
> feat: expanding the functionality of utils.sh and combining functions

- test/utils.sh
- unittests_bash/test_utils.bats
`opm render` on a bundle will always add that bundle image to the related images. When processing related images for a bundle, however, we do not want a self-reference.
> fix(KFLUXSPRT-1555): remove bundle images from their related image

- test/utils.sh
- unittests_bash/test_utils.bats
1. Fix get_unreleased_bundles returning a jq error 
The variables that were passed to jq --argjson were not valid json arrays
2. Modify get_highest_bundle_version to return a bundle image field rather than a bundle name
Signed-off-by: Anna Rania <asergien@asergien-thinkpadp1gen3.bos.csb>
> fix(CVP-4421): get_unreleased_bundles returns a jq error

- test/utils.sh
- unittests_bash/test_utils.bats
Memory consumption when slurping in the fbc and index metadata was necessitating bumping the memory for pods. We can instead do this set subtraction in a more efficient way directly in bash.
> fix: improve memory utilization and validation errors

- test/utils.sh
- unittests_bash/test_utils.bats
the function only checked for amd64 image manifests and returned null for images of other arch causing the execution to fail. This commit fixes that behavior.
> fix(CVP-4376): ensure get_base_image handles non-amd64 images

- test/utils.sh
- unittests_bash/test_utils.bats
This commit adds a get_bundle_arches function which takes rendered FBC, bundle image and FBC fragment's target OCP version, and returns bundle supported architectures.
> feat(CVP-4399): add function to get bundle's arches

- test/utils.sh
- unittests_bash/test_utils.bats
This commit adds group_bundle_images_by_package function which takes 
rendered FBC, bundle image(s), and returns a map of
{"package1":["bundleImage1"],"package2":["bundleImage2"]}
> feat(CVP-4397): add function to group bundle images by package

- policies/clair/vulnerabilities-check.rego
- unittests/test_data/clair.json
This change achieves the required behavior doescribed in convo, that only RHSA fixes are considered as patched vulnerabilities, any others are set as unpatched.
> fix(KONFLUX-5903): set only RHSA vulns as patched ones

- .github/workflows/clam-db.yaml
- .github/workflows/clam-ver-check.yaml
- .github/workflows/pr-checks.yaml
- .github/workflows/release.yaml
The ubuntu-20.04 image for github actions is being deprecated. Workflows that still rely on the image after April 1, 2025 willl no longer work. We need to update to ubuntu-24.04 to avoid this.
> chore(stoneintg-1134): update github workflows to ubuntu-24.04

- .github/dependabot.yml
* this is because Pat has left integration-service team and I would like to make his life a litte bit better.
> chore: remove Pat from dependabot.yaml

- test/utils.sh
- unittests_bash/test_utils.bats
This commit changes regex in get_highest_version_from_bundles_list to be able to process bundle versions with additional suffixes, for example, v4.99.0-0.1738868945
> fix: fix regex to process bundle versions with suffixes

- test/utils.sh
- unittests_bash/test_utils.bats
This commit adds three functions:
* get_bundle_suggested_namespace: Given 'opm render $bundle_image', this function returns the suggested namespace for the bundle
* get_bundle_install_modes: Given 'opm render $bundle_image', this function returns the supported install modes for the bundle
* get_bundle_name: Given 'opm render $bundle_image', this function returns the bundle name
> feat(CVP-4400): add functions for operator installation test

- Dockerfile
Add -L flag to openshift-client download so that build works in konflux
> chore: add -L flag to openshift-client download

- policies/clair/vulnerabilities-check.rego
Signed-off-by: Jiri Sztuka <jsztuka@redhat.com>
* Rego policy was excluding vulnerabilities that did not have RHSA fix
* This change incudes those also
> fix(KFLUXSPRT-2516): fix rego policy

- .gitlint
* ignore author red-hat-konflux in .gitlint since the pr from it has long title and Signed-off-by, such as https://github.com/konflux-ci/konflux-test/pull/408
Signed-off-by: Hongwei Liu <hongliu@redhat.com>
> chore: ignore author red-hat-konflux in .gitlint

- test/utils.sh
- unittests_bash/test_utils.bats
Return null instead of exiting with code 1 when suggested-namespace annotation is missing. Since the deployment test  will create a namespace if needed, failing early is unnecessary.
> fix: return null when suggested-namespace annotation is not defined

- clamav/Dockerfile
Adding `findutils` to the microdnf install list of packages.  This is to make `find` available to the updates to the clamav-scan task that adds parallel processing for performance improvement.  See PR: https://github.com/konflux-ci/build-definitions/pull/2262
> feat: added findutils to clam-db image for parallel processing

- test/utils.sh
- unittests_bash/test_utils.bats
This commit adds a new function that takes a FBC fragment image, and checks the number of manifests.
If the image is an index (multi-arch), replace the digest with the 0th manifest's digest;
If it's a single-arch image manifest, leave it unchanged.
Related slack thread: https://redhat-internal.slack.com/archives/C074JM28DTP/p1746026536055699
> feat(CLOUDDST-27082): resolve arch specific digest

- Dockerfile
* Add the opa utility to the konflux-test image
* This is needed to enable the integration test to run OPA unit tests
> feat(STONEINTG-1156): add the opa util to konflux-test

- integration-tests/konflux_test_validation.yaml
* Add the integration test pipeline which runs validation tests for the konflux-test image, migrating from the github actions
* The shellcheck tasks runs shellcheck on bash code
* The self-check task executes the self check script which runs the functional tests that are present on the image
* The unit-test task executes the bats bash unit tests and the opa rego policy unit tests
See [example pipelineRun](https://konflux-ui.apps.stone-prd-rh01.pg1f.p1.openshiftapps.com/ns/rhtap-integration-tenant/applications/konflux-test/pipelineruns/validation-shxlt) and it's [check run](https://github.com/konflux-ci/konflux-test/pull/436/checks?check_run_id=42646444432) that was executed for this PR: 
> feat(STONEINTG-1156): add validation integration test pipeline

- .github/workflows/pr-checks.yaml
- integration-tests/konflux_test_validation.yaml
- rpms.lock.yaml
- test/selftest.sh
- unittests_bash/data/cosign_test_data.json
- unittests_bash/test_cosign.bats
This PR adds complete unit testing coverage for the cosign tool across all environments in the konflux-test security testing framework.
Functionality Tested:
Basic Operations
✅ Version checking
✅ Help command functionality
✅ Binary location verification
Core Commands
✅ cosign verify - signature verification
✅ cosign generate-key-pair - key generation
✅ cosign triangulate - signature location
✅ cosign tree - artifact relationships
✅ cosign verify-blob - blob verification
For more info [STONEINTG-1120](https://issues.redhat.com/browse/STONEINTG-1120)
> feat(STONEINTG-1120): add unit tests for covering cosign
