- .yamllint
Add yamllint configuration file
Signed-off-by: Sri Vignesh [sselvan@redhat.com](mailto:sselvan@redhat.com)
> Add yamllint to hacbs-test repo

- .github/workflows/pr-checks.yaml
Add validation for dockerfile on each PR
> Add dockerfile validation

- .github/workflows/pr-checks.yaml
- Dockerfile
- README.md
- action.yml
- test/conftest.sh
- test/entrypoint.sh
Follow up from https://github.com/redhat-appstudio/hacbs-test/pull/8 
Didn't close #8 intentionally.
> Add Conftest Integration test

- policies/image/inherited-labels.rego
- test/conftest.sh
- unittests/test_data/image.json
- unittests/test_images/deprecated-labels_test.rego
- unittests/test_images/inherited-labels_test.rego
- unittests/test_images/optional-labels_test.rego
- unittests/test_images/required-labels_test.rego
* Add the inherited labels policy with unit/integration tests
* Add the good_image and bad_image to unit test data
* Refactor the existing unit tests to use the bad_image
> [HACBS-202] Add the inherited labels policy

- Dockerfile
- test/entrypoint.sh
1. Remove API_KEY from rpm cmd, JSON is generated even without the API_KEY.
2. Update contest.sh path while running via docker run cmd.
> Update rpm manifest cmd

- .github/workflows/README.md
- .github/workflows/release.yaml
- README.md
1. Update README.md file with prerequisites.
2. Update release workflow README.md file with Indentation and some minor changes.
> Update README.md changes

- Dockerfile
- test/entrypoint.sh
Signed-off-by: Jing Qi <jinqi@redhat.com>
The cmd to run the image:
docker run --privileged --rm -it --env "SNYK_TOKEN=***" \
-v "path_app_source_code:/app:Z"  hacbs_test_image
> Add snyk code test in hacbs-test image

- Dockerfile
Needed for handling clamav scan output.
> [HACBS-337]-Adding python binary

- Dockerfile
Needed for additional datetime parsing to isoformat.
> feat: Adding dateutil module

- .github/workflows/clam-db.yaml
- .github/workflows/release.yaml
- Dockerfile
This PR is to add ppc64le support to hacbs-test and clamav-db images.
> Add ppc64le support

- Dockerfile
> feat(HACBS-1213): add CycloneDX CLI

- policies/image/fbc-labels.rego
- test/conftest.sh
- test/entrypoint.sh
- unittests/test_images/fbc-labels_test.rego
> feat(HACBS-1436): add fbc label check policy

- .github/workflows/pr-checks.yaml
- Dockerfile
- clair-in-ci/Dockerfile
- clamav/Dockerfile
Multiple dockerfile fixes, for details please see particular commits
> Dockerfile fixes

- Dockerfile
- test/selftest.sh
Signed-off-by: Jiri Sztuka <jsztuka@redhat.com>
This change is needed as prerequisite for upcoming PR creation in build-definitions.
> feat(1509): Adding yq to worker image

- .github/dependabot.yml
GH actions will be updated automatically to the latest releases
> chore(HACBS-1634): configure dependabot to update GH actions

- .github/workflows/release.yaml
Replacing custom actions which are without updates and are deprecated with their original counterparts
> fix(workflow): update actions in release workflow

- .github/workflows/clair-in-ci-db.yaml
Verified that the change is casuing issues on my personal branch.
> fix(clair-in-ci): workflow-job

- test/utils.sh
- unittests_bash/test_utils.bats
Update according the review result in https://github.com/redhat-appstudio/build-definitions/pull/331
* remove 'the'
* Expression improvement in log
> fix(STONEINTG-205): remove the from log

- .github/gitlint/description_conventional_commits.py
- .github/workflows/pr-checks.yaml
- .gitlint
Enforce convetional commits and signed-off using gitlint
> chore(STONEINTG-129): enforce conventional commits

- policies/clair/vulnerabilities-check.rego
- unittests/test_clair/vulnerabilities-check_test.rego
Detection of vulnerabilities in clair results will be reported as warnings rather than violations.
> fix(STONEINTG-360): change violations to warnings for Clair rego policy

- .github/workflows/README.md
Remind releaser to use semver during release
> chore(release): document using semver

- test/conftest.sh
- test/selftest.sh
* Test the newly built images in selftest.sh
* Add the test for the invalid fbc image
> chore(STONEINTG-439): use new example images in selftests

- test/conftest.sh
- test/selftest.sh
Block CI by failing when test fails.
> fix(selftest): fail task when test failed

- test/utils.sh
generate TEST_OUTPUT in expected step only
Signed-off-by: Hongwei Liu <hongliu@redhat.com>
> feat(STONEINTG-222): generate TEST_OUTPUT in expected step only

- test/utils.sh
- unittests_bash/test_utils.bats
> Add a function to get image manifests of an image index

- policies/clair/vulnerabilities-check.rego
- unittests/test_clair/vulnerabilities-check_test.rego
- unittests/test_data/clair.json
* Update the clair policies to differentiate between fixed and unpatched vunlerabilities
> feat(STONEINTG-877): add unpatched_vulnerabilities to clair policy

- unittests_bash/test_utils.bats
When I first encountered this, I didn't understand what was failing.
> ci(mocks) improve error message for skopeo mock

- .github/workflows/clam-ver-check.yaml
Fix for daily clamav version checker script.
> fix(STONEINTG-1031): add whitespace before closing bracket

- policies/clair/vulnerabilities-check.rego
- unittests/test_clair/vulnerabilities-check_test.rego
- unittests/test_data/clair.json
* Add "Negligible" severities to the count of low vulnerabilities in the clair policy
> feat(STONEINTG-865): process "Negligible" clair severity

- .github/workflows/clam-db.yaml
Added new secrets user and token for the new Quay Robot user was added to repo [quay.io/konflux-ci/clamav-db](https://quay.io/repository/konflux-ci/clamav-db?tab=settings)
> feat(STONEINTG-947): added login to the new quay repo and used new robot

- Dockerfile
> fix: resolve ppc64le build issues

- .github/workflows/build_reusable.yaml
- .github/workflows/clam-ver-check.yaml
Updating all references to quay repo to reflect org change to konflux-ci.
> feat(STONEINTG-946): migrate redhat-appstudio/konflux-test

- .github/workflows/build_reusable.yaml
Fix duplicite IDs in workflow script.
> fix duplicite IDs for steps

- Dockerfile
> fix: certificate issues with ppc64le

- test/utils.sh
- unittests_bash/test_utils.bats
The set of related images will only continue to grow for a FBC fragment as bundles are added to the packages' channels. Once fragments are released and become part of the target index, we no longer need to consider the validity of these related images. Therefore, we want to be able to determine the set of unique unreleased related images for an FBC fragment so that we know the minimal set of pullspecs that might need to be further inspected and/or verified.
> Identify all unreleased related images for an FBC fragment

- Dockerfile
> fix: check-payload tool download method

- test/utils.sh
Following on from #364, further reducing memory requirements by storing extracted content in files and processing it there without using jq.
There will likely need to be further improvements later for KONFLUX-6954 including being able to reuse specific caches so fewer render operations are needed.
> fix(KONFLUX-6954): stop storing extracted metadata in variables

- test/utils.sh
- unittests_bash/test_utils.bats
This commit:
* adds a function get_highest_version_from_bundles_list: Given the output of 'opm render $fbc_fragment' command, a package name, a channel name, and a bundle images list this function returns the highest bundle version from the provided BUNDLE_IMAGES list
* fixes get_bundle_arches function to explicitely check for "supported" value of the operatorframework.io/arch. key
> feat(CVP-4397): add function to get highest bundle from bundles list

- .github/workflows/build_reusable.yaml
- Dockerfile
Update check-payload to 0.3.5 to solve issue for the secondary-scheduler-operator team.
See also KFLUXSPRT-2384
> fix(CLOUDDST-26534): update check-payload to 0.3.5

- test/utils.sh
- unittests_bash/test_utils.bats
Introduced a retry function that skopeo and opm commands can use. This will make things a bit more resilient when inspecting/copying/rendering images on remote registries. In particular, this can help where an initial request may encounter a "bad gateway" error, but a subsequent request may succeed.
The retry function is derived from that used in build-definitions here:
https://github.com/konflux-ci/build-definitions/blob/094f07ae89bc1cfe2c40910c84cfb9231ce4ec42/hack/build-and-push.sh#L106
> fix(KONFLUX-7459): retry skopeo and opm commands

- Dockerfile
> fix: add retry script to the quay.io/konflux-ci/konflux-test

- README.md
The main purpose of this repo is to store resources used in Konflux tekton tasks and pipelines such as tools, conftest
policies and bash utility functions.
> doc: update README introduction

- Dockerfile
> Update check-payload version to 0.3.7

- test/utils.sh
- unittests_bash/test_utils.bats
Given a scorecard config yaml, collect_scorecard_config_images function extracts unique image references defined under .stages[].tests[].image.
It returns a sorted list of these unique image references, one per line.
> feat(CLOUDDST-27593): add function to collect scorecard config images

- .github/CODEOWNERS
- .github/dependabot.yml
* Add the CODEOWNERS file
* Remove the reviewers from dependabot config
> chore: add CODEOWNERS

- .tekton/konflux-test-pull-request.yaml
- .tekton/konflux-test-push.yaml
- Dockerfile
Required to pass Conforma checks
> chore: use registry.redhat.com cosign image

- test/utils.sh
- unittests_bash/test_utils.bats
This commit adds a get_uncompressed_layer_digests function. Given container image it returns a list of uncompressed layer digests one per line.
I used an existing CVP function as an example: https://gitlab.cee.redhat.com/cvp/pipeline/-/blob/master/src/org/cvp/pipeline/OperatorUtils.groovy?ref_type=heads#L597
> feat(CLOUDDST-27962): add get_uncompressed_layer_digests

- test/utils.sh
- unittests_bash/test_utils.bats
replace_mirror_pullspec_with_source function which will be used by tasks in build-definitions
This helper function replaces mirrored image pullspecs in a catalog.json
file with their original source locations. It uses an
ImageDigestMirrorSet file as the mapping reference.
This utility is needed for CI tasks within the `build-definitions`
repository to ensure images are resolved to their true source.
Signed-off-by: Jan Lipovský <jlipovsk@redhat.com>
[CLOUDDST-27030]
[KONFLUX-5311]
> feat(KONFLUX-5311): Adding replace_mirror_pullspec_with_source

- .github/CODEOWNERS
> chore: add Nigel to the codeowners config

- policies/clair/vulnerabilities-check.rego
- policies/clamav/virus-check.rego
- policies/image/deprecated-labels.rego
- policies/image/fbc-labels.rego
- policies/image/inherited-labels.rego
- policies/image/optional-labels.rego
- policies/image/required-labels.rego
- policies/repository/deprecated-image.rego
- policies/rpm_manifest/unsigned-rpms.rego
- unittests/test_clair/vulnerabilities-check_test.rego
- unittests/test_clamav/virus-check_test.rego
- unittests/test_images/deprecated-labels_test.rego
- unittests/test_images/fbc-labels_test.rego
- unittests/test_images/inherited-labels_test.rego
- unittests/test_images/optional-labels_test.rego
- unittests/test_images/required-labels_test.rego
- unittests/test_repository/deprecated-image_test.rego
- unittests/test_rpm_manifest/unsigned-rpm_test.rego
Builds upon:
- #572 
Adds a commit to enable OPA v1 with backwards compatibility for all rego files.
> [take-2] Add `if` to align with OPA v1
